import type {Metadata} from 'next';
import {Roboto} from 'next/font/google';
import '@/styles/globals.css';

const roboto = Roboto({
    subsets: ['latin'],
    display: 'swap',
    weight: ['400', '500', '700', '900'],
    variable: '--font-roboto',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function LoginLayout({children}: {children: React.ReactNode}) {
    return (
        <html lang="en">
            <body className={`${roboto.variable}`}>

                {children}
                </body>
        </html>
    );
}
