import { Metadata } from "next";
import { AuthProvider } from "@/contexts/AuthContext";

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function LoginLayout({ children }: { children: React.ReactNode }) {
    return (
        <main>
            <AuthProvider>
                {children}
            </AuthProvider>
        </main>
    );
}
