import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import '@/styles/globals.css';
import { Providers } from "@/app/providers";
import Header from "@/components/header";
import Footer from "@/components/footer";

const roboto = Roboto({
    subsets: ['latin'],
    display: 'swap',
    weight: ['400', '500', '700', '900'],
    variable: '--font-roboto',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={`${roboto.variable}`}>
                <main className="flex min-h-screen flex-col items-center justify-center bg-gray-100 md:px-0 px-4">
                    <Providers>
                        <Header />
                        <div className="flex-grow py-8">
                            {children}
                        </div>
                        <Footer />
                    </Providers>
                </main>
            </body>
        </html>
    );
}
